### ISSUE TITLE
Showing non-contrib extensions

### ISSUE THREAD

**Issue by AbdealiJK** [Jupyter-contrib/jupyter_nbextensions_configurator#101]
### Context
I have some extensions I have custom written.
A simple example of an extension is the "Hide Cluster Tab" extension which just hides the "Cluster" tab in the topbar.

I was looking at way configurator recommended an extension setup and tried following it:

```
/opt/myexts/hide_cluster_tab
├── hide_cluster_tab.yml
├── main.css
├── main.js
└── readme.md
```

I then opened Nbextension tab, and found my extension was visible:
<img width="295" alt="Screen Shot 2019-08-13 at 9 34 57 PM" src="https://user-images.githubusercontent.com/2200743/62957331-38043780-be12-11e9-9d7f-7979663b2a18.png">

### Question
Why does it appear twice ? And how can I make it appear only once.

### Debug Info

And I set the nbextension path config in `jupyter_notebook_config.py:
```python
c.NotebookApp.extra_nbextensions_path = [
    '/opt/myexts',
]
```
And to enable my extension ran:
`jupyter nbextension enable hide_cluster_tab/main --sys-prefix --section=tree`

hide_cluster_tab.yml:
```yml
Type: Jupyter Notebook Extension
Name: Hide Cluster Tab
Description: This extension hides the cluster tab in Jupyter
Link: readme.md
Main: main.js
Compatibility: 3.x, 4.x, 5.x
```

main.css:
```css
a.clusters_tab_link {
  display: none !important;
}
```

main.js:
```js
define([
    'jquery',
    'require',
], function($, requirejs) {
    "use strict";

    var load_extension = function() {
        // Add the CSS needed for this extension.
        $('<link/>')
            .attr('rel', 'stylesheet')
            .attr('type', 'text/css')
            .attr('href', requirejs.toUrl('./main.css'))
            .appendTo('head');
    }

    var extension = {
        load_jupyter_extension : load_extension,
        load_ipython_extension : load_extension
    };
    return extension;
});
```

readme.md:
```md
Hide Cluster Tab
================

This extension hides the "cluster" tab.
```
